### ISSUE TITLE
I cant see the logs on Chrome Dev Tools with React Native

### ISSUE THREAD

**Issue by matthewfang** [winterbe/mobx-logger#10]
![image](https://cloud.githubusercontent.com/assets/20057066/23900772/611f06ec-08f5-11e7-9938-bf260da49de1.png)

predicate get true, but i also cant see the logs on chrome , how can i get it works?

**Comment by yordis** [comment]
@winterbe Hey man, I recently start using MobX and I don't see any logs as well. Any ideas what could be?

**Comment by Kennytian** [comment]
@matthewfang  @yordis  Hello, all!  I use [React Native Debugger](https://github.com/jhen0409/react-native-debugger) can see logs

**Comment by winterbe** [comment]
I close this issue as I cannot reproduce the issue.
