### ISSUE TITLE
How to print out all store states after each action?

### ISSUE THREAD

**Issue by joeyzhao0113** [winterbe/mobx-logger#11]
Whether it supports printing out all store state values? It would be very handy.

**Comment by winterbe** [comment]
You can expand logged actions in the console to access various information such as action parameters and also the underlying store.

Example:

![bildschirmfoto 2018-03-26 um 13 59 15](https://user-images.githubusercontent.com/485033/37905113-1cbabef6-30fe-11e8-92da-904ec527cfb9.png)
