### ISSUE TITLE
it dosent work on mobx 3.1.0  with ReactNative

### ISSUE THREAD

**Issue by matthewfang** [winterbe/mobx-logger#9]
enableLogging({
                predicate: () => __DEV__ && Boolean(window.navigator.userAgent),
            });

it dosent log anything on the console

**Comment by megahertz** [comment]
Did you try to use the polyfill:
```js
if (!console.groupCollapsed) {
  console.groupCollapsed = console.log.bind(console);
  console.groupEnd = () => {};
}
```

**Comment by winterbe** [comment]
Your code is wrong, you have to check flag `__DEV__` not `DEV` (notice the underscores).
